/*create database LogisticBot;
use LogisticBot;*/
DROP TABLE user_subs;
DROP TABLE categories;
CREATE TABLE user_subs(
userid INT NOT NULL,
category VARCHAR(255) NOT NULL,
date_start date,
CONSTRAINT pk_user_sub_ID PRIMARY KEY (userid,category)
);
CREATE TABLE categories(
AUC_NUM INT PRIMARY KEY,
OPEN_DATE DATE NOT NULL,
OPEN_TIME TIME NOT NULL,
CLOSE_DATE DATE NOT NULL,
AUC_NAME VARCHAR(255) NOT NULL,
AUC_STATUS VARCHAR(255) NOT NULL,
CATEGORY VARCHAR(255) NOT NULL,
ORG_IDFOREIGN INT NOT NULL
);
