/*create database LogisticBot;
use LogisticBot;*/
CREATE TABLE user_subs(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
userid INT NOT NULL,
category VARCHAR(100) NOT NULL,
date_start date
);
CREATE TABLE categories(
AUC_NUM INT PRIMARY KEY,
OPEN_DATE date NOT NULL,
OPEN_TIME date NOT NULL,
CLOSE_DATE date NOT NULL,
AUC_NAME VARCHAR(100) NOT NULL,
AUC_STATUS VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(100) NOT NULL,
ORG_IDFOREIGNINT NOT NULL
);
